name: water
description: Water shop application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  video_player: ^2.1.6
  shared_preferences: ^2.0.6
  get_it: ^7.1.3
  http: ^0.13.3
  responsive_framework: ^0.1.4
  cached_network_image: ^3.1.0

  # graphics
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  lottie: ^1.1.0

  # animations
  animations: ^2.0.1

  # bloc
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3

  # localization
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0

  # social auth
  flutter_facebook_auth: ^3.5.0
  google_sign_in: ^5.0.4
  sign_in_with_apple: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.1

flutter_icons:
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/images/
    - assets/images/categories/
    - assets/images/products/
    - assets/lottie/
    - assets/svg/
    - assets/video/
    - google_fonts/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
